version: '3.8'

services:
  scrapper-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrapper-api
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      # Montar volumes para persistir dados
      - ./data:/app/data
      - ./live_data:/app/live_data
      - ./live_data_simplify:/app/live_data_simplify
      - ./analysis:/app/analysis
      - ./logs:/app/logs
    restart: unless-stopped
    # Configurações necessárias para Playwright no Docker
    shm_size: 2gb
    security_opt:
      - seccomp:unconfined
    # Limitar recursos se necessário (descomente se necessário)
    # mem_limit: 2g
    # cpus: '1.0' 