services:
  web-app:
    container_name: nextjs-web-app
    build:
      context: .
      args:
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    ports:
      - "3001:3000"
    restart: unless-stopped


